__author__ = 'David Reilly'

"""
    Project Euler
    Problem: 2

    'Each new term in the Fibonacci sequence is generated by adding the previous two terms.
        By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
        find the sum of the even-valued terms.'

"""

def generate_fibonacci(returns, upper_bound):

    first = 1
    second = 2
    third = 3

    while third < upper_bound:

        if returns == "even":
            if third % 2 == 0:

                yield third

            first = second
            second = third
            third = first + second

        else:
            if third % 3 == 0:
                yield third

            first = second
            second = third
            third = first + second


def sum_fibonacci(returns="even", upper_bound=4000000):

    if returns == "even":
        return sum(generate_fibonacci(returns, upper_bound)) + 2

    else:
        return sum(generate_fibonacci(returns, upper_bound)) + 1

if __name__ == "__main__":

    sumz = sum_fibonacci()

    print sumz